config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  get 'events/index'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.all
  end
 
  def new
    @events = Event.new
    respond_to do |format|
      format.html
      format.js
    end
  end
 
  def create
    @events = Event.all
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html
        format.js
      else
        format.js {render :new}
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :memo, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<tbody>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.memo %></td>
    <td><%= event.start_date %></td>
    <td><%= event.end_date %></td>
    <td><%= link_to 'Show', event_path(event) %> 
    <td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</tbody>

app/views/events/_form.html.erb
<%= simple_form_for @events, remote: true do |f| %>
  <p><%= f.input :title %></p>
  <p><%= f.input :memo %></p>
  <p><%= f.input :start_date %></p>
  <p><%= f.input :end_date %></p>
  
  <%= f.button :submit ,"追加" %>
<% end %>

app/views/events/_index.html.erb
<%= render @events %>

app/views/events/create.js.erb
$('#events').html("<%= j (render 'index') %>");
$('#event-form').fadeOut(600);

app/views/events/index.html.erb
<h1>Event一覧</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Memo</th>
      <th>Start_date</th>
      <th>End_date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%= render @events %>
</table>

<br>

<body>
  <% link_to "データを追加する", new_event_path, remote: true %>
 
  <div id="mask" class="hidden"></div>
      <section id="modal" class="hidden">
      
        <div id="event-form"></div>

        <div id="close">
        閉じる
        </div>
      </section>

  <div id="calendar"></div>

</body>

app/views/events/new.js.erb
$('#event-form').html("<%= j (render 'form') %>");
$('#event-form').fadeIn(800);

app/views/events/show.html.erb
<h1>show</h1>

<p>
<%= @event.title %>
</p>
<p>
<%= @event.memo %>
</p>
<p>
<%= @event.start_date %>
</p>
<p>
<%= @event.end_date %>
</p>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalenderApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  </body>
</html>